### ISSUE TITLE
Caps all ceramics?

### ISSUE THREAD

**Issue by KeLaiFu** [m0xpd/encore#2]
Are all the non polarised caps just standard ceramics? There's a variety of different footprints on the board. not sure if the more rectangular ones are normally film caps of its just different sized ceramics?

thanks for the reply on my other question too btw.

**Comment by m0xpd** [comment]
Hi again KeLaiFu

Here are details of the capacitors:

De-coupling capacitors C1, C2, C12, C13, C9, C20, C21 and modulate/de-modulate capacitors for the PT2399, C23, C24, C30, C32 (all having value quoted as “0.1u” in the BoM) are disc ceramics with 0.2-inch pitch.

Filter / coupling capacitors (C5, C7, C8, C14, C15, C16, C17, C18, C19, C25, C27, C28, C31, C33) are ceramics (for pF values), or multi-layer ceramics (for nF values) with 0.1-inch pitch.

Polarized capacitors with 0.1-inch pitch are used for power supply smoothing (C3, C4, C10, C11), smoothing the mid-rail voltage of the PT2399 (C22) and d.c. blocking (C26, C29).

There is no 'C6', due to an indexing error on my part.

Thanks for your continued interest in encore!

**Comment by m0xpd** [comment]
I added the information above to:
https://github.com/m0xpd/encore/tree/main/PCBs
so everybody can benefit from your useful question.
